language: c

sudo: required
dist: trusty

compiler:
  - gcc
  - clang

before_script:
  - autoreconf -i

script:
  - ./configure && make && make check

after_failure:
  - find ./tests -name '*.log' -print -exec cat {} \;

matrix:
  include:
    - compiler: clang
      os: osx
